Issue 78 create tasks view
codersforcauses/penni pull request #102
Opened 2024-07-09 09:37 UTC by K1rk3y

## Change Summary
Work in progress, will update asap.

### Change Form

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

2024-07-15 05:30 UTC, yunho7687 commented
@0XFF-96 could you please review this PR?

2024-07-20 05:55 UTC, CodeWithTheDoctor requested changes
Great work! Was confused by the two serialisers files though, have a look.

2024-07-20 05:55 UTC, CodeWithTheDoctor commented on server/app/serializers.py
I noticed there are two serialiser files: seriali*s*er.py and seriali*z*ers.py
Is one of them redundant?

2024-07-20 05:58 UTC, K1rk3y commented on server/app/serializers.py
I have removed the redundant file.

2024-07-20 06:05 UTC, yunho7687 approved these changes

2024-07-20 06:07 UTC, CodeWithTheDoctor approved these changes

2024-07-20 06:07 UTC, YunhuiZ approved these changes

2024-07-20 06:08 UTC, merged