add views, urls, serializers for bids
codersforcauses/penni pull request #103
Opened 2024-07-09 17:49 UTC by YunhuiZ

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2024-07-10 14:50 UTC, 0XFF-96 requested changes, later dismissed

2024-07-10 14:50 UTC, 0XFF-96 commented on server/app/urls.py
> +router.register(r'tasks/(?P<task_id>\d+)/bids', BidsViewSet, basename='bids')
prefer to use django url dispatch instead of raw pattern. 

URL dispatcher: https://docs.djangoproject.com/en/5.0/topics/http/urls/#path-converters

2024-07-11 15:47 UTC, YunhuiZ commented on server/app/urls.py
> +router.register(r'tasks/(?P<task_id>\d+)/bids', BidsViewSet, basename='bids')
thanks and changed.

2024-07-11 15:55 UTC, YunhuiZ commented on server/app/urls.py
@0XFF-96 I have removed raw URL pattern and pls help check here,

2024-07-20 05:57 UTC, 0XFF-96 approved these changes

2024-07-20 05:59 UTC, 0XFF-96 commented
@yunho7687

2024-07-20 07:26 UTC, yunho7687 approved these changes

2024-07-20 07:48 UTC, merged