Modified borders for icons
codersforcauses/penni pull request #136
Opened 2024-07-15 15:14 UTC by MahitGtg

## Change Summary
Shortened the borders according the figma for icons
<img width="338" alt="Screenshot 2024-07-15 at 11 13 50 PM" src="https://github.com/user-attachments/assets/9cd9f13a-aba1-4f99-b524-54a0f823faec">

## Other Information
Resolves #133 

# Related issue

- Resolve #133

2024-07-15 15:22 UTC, ErikaKK requested changes

2024-07-15 15:22 UTC, ErikaKK commented on client/src/components/ui/profile-tags.tsx
With your current layout, it is hard to put the border in the right position as Figma design. Also, Pls change the font to penni style font.

2024-07-15 15:24 UTC, ErikaKK commented on client/src/components/ui/profile-tags.tsx
Your current layout put the arrow icon in a separate div. It would be easier if you put it with the texts in a same flexbox then you can set the bottom border for this flexbox

2024-07-22 08:44 UTC, CodeWithTheDoctor commented on client/src/components/ui/profile-tags.tsx
@MahitGtg Has this been resolved?

2024-07-22 09:45 UTC, allyharrison commented on client/src/components/ui/profile-tags.tsx
@CodeWithTheDoctor ooh sorry that's on me, I was helping him out with this on Sat. I'll commit my changes a bit later tonight 💆

2024-07-22 15:21 UTC, allyharrison commented on client/src/components/ui/profile-tags.tsx
Okay I've pushed my changes.
As the Logout section doesn't have subtitle text, it's a little more finicky to make it the same size as the other sections. If someone else wants to have a go at making it look more like the Figma, please do:
![image](https://github.com/user-attachments/assets/2375f9ea-81d6-4162-a16e-f2f9e474a464)
![image](https://github.com/user-attachments/assets/3aefe6e1-a548-4391-84be-9fda109b4510)

Ahh I just noticed the About icon is upside down too, but I won't be able to do anything about it until tomorrow night. Again, if anyone else wants to do it before I get back to it, feel free!

2024-07-23 07:22 UTC, MahitGtg commented on client/src/components/ui/profile-tags.tsx
Issues sorted:
1. Resolved the upside down info icon.
2. Made all the Profile-tag component of standard height.
3. Linked payouts page with profile page.

2024-07-23 09:08 UTC, ErikaKK approved these changes
lgtm

2024-07-23 09:09 UTC, MahitGtg commented on client/src/components/ui/profile-tags.tsx
@yunho7687 @CodeWithTheDoctor the pr is ready to be reviewed!

2024-07-23 11:44 UTC, merged