Issue 22 bidder s tasks page
codersforcauses/penni pull request #142
Opened 2024-07-17 15:49 UTC by ErikaKK

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
Using mock data in `/pages/api/tasks-test.tsx` to test the UI of bidder page. Created dynamic route for task detail. All works fine.
<img width="290" alt="image" src="https://github.com/user-attachments/assets/40b58299-6143-4586-8b68-a5f23ef003bc">
<img width="314" alt="image" src="https://github.com/user-attachments/assets/fc2f52b5-f77d-497b-ba0a-e52c2c4407d3">

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
- Still need to change some onClick value change
- Need to add sending req to server to get data or update database
- I'm not sure of the date format in database, so may need to change date comparison later

2024-07-18 03:54 UTC, yunho7687 requested changes

2024-07-18 03:54 UTC, yunho7687 commented on client/src/pages/component-showcase.tsx
> +            <BottomNav isFixed={false} children={<></>} />
maybe you can just delete this? and there are some conflicts with the main branch, please run `git merge origin main` and try to fix it
```suggestion
            <BottomNav isFixed={false} 
```

2024-07-19 09:53 UTC, SodaVolcano approved these changes
Sorry for the late review and looks good to me (wow that's a lot of changes)

2024-07-19 10:56 UTC, yunho7687 approved these changes

2024-07-19 11:22 UTC, merged