Issue 48 form component
codersforcauses/penni pull request #98
Opened 2024-07-08 06:38 UTC by SodaVolcano

## Summary
Created (very over-engineered) `<Form>` component consisting of a collection of input components (submit button is NOT included, add it yourself)
- Pass it a JSON object defining the fields and it'll internally manage the states and titles/subtitles
    - So we don't clutter the code with a bunch of `useState(...)`
- Form data is represented as `(name, value)` pairs to the `onSubmit` function (only inputs with `name` attribute are included)
- Example usage is in `component-showcase.tsx`

Also removed margins from callouts and inputs, should be set by the user.

![image](https://github.com/codersforcauses/penni/assets/100743188/a24ae3b8-e6fa-482d-8feb-5dc1ceb777e5)

Values passed to `onSubmit(...)` (note: last field is missing `name` so it's not included in the list of form data)
![image](https://github.com/codersforcauses/penni/assets/100743188/dd7998b2-72b1-4421-a672-2a3cb0594220)

2024-07-08 12:14 UTC, ErikaKK requested changes

2024-07-08 12:14 UTC, ErikaKK commented on client/src/components/ui/form.tsx
Should add some value validation: only when all the input values are provided can the user submit the form. 
Is it better to make a form component that looks the same as the new task form?
<img width="221" alt="image" src="https://github.com/codersforcauses/penni/assets/98962967/0f7ae68e-86a8-4c6d-8476-39e6af0ab1b0">

2024-07-09 04:09 UTC, SodaVolcano commented on client/src/components/ui/form.tsx
I fould out about `useContext()` so I'm rewriting this component so it's a bit more flexible and easier to use while still allowing it to manage the states of the inputs

2024-07-09 09:03 UTC, yunho7687 commented
<img width="851" alt="Screenshot 2024-07-09 at 5 02 56 PM" src="https://github.com/codersforcauses/penni/assets/75521446/1dbd0709-3dd3-4d92-9f43-59795ad5692b">
there is a conflict now. Please resolve this conflict before able to merge

2024-07-10 15:07 UTC, SodaVolcano commented
Note: used `<Button>` variant `inactive` which will be pushed by #107

2024-07-11 04:25 UTC, yunho7687 approved these changes

2024-07-11 04:28 UTC, ErikaKK approved these changes
It looks good. May create new issue for input required validation with style change in the submit button. @ArcueidShiki can have a look at it

2024-07-11 04:28 UTC, merged